
server:
  port: 8080

sharding:
  jdbc:
    datasource:
      names: ds0,ds1
      ds0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class: com.mysql.jdbc.driver
        url: jdbc:mysql://localhost:3306/db_1?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
        username: root
        password:
        maxPoolSize: 50
        minPoolSize: 1
      ds1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class: com.mysql.jdbc.driver
        url: jdbc:mysql://localhost:3306/db_2?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
        username: root
        password:
        maxPoolSize: 50
        minPoolSize: 1
    config:
      sharding:
        default-data-source-name: ds0
        tables:
          t_order:
            actual-data-nodes: ds$->{0..1}.t_order$->{0..1}
            database-strategy:
              standard:
                sharding-column: create_time
                preciseAlgorithmClassName: com.simon.db.sharding.OrderTimePreciseShardingAlgorithm
              #inline:
                #sharding-column: uid
                #algorithm-expression: ds$->{uid % 2}
            table-strategy:
              inline:
                sharding-column: id
                algorithm-expression: t_order$->{id % 2}
            keyGeneratorColumnName: id

      #masterslave:
        #name: ms
        #master-data-source-name: ds0
        #slave-data-source-names: ds1
      props:
        sql.show: true
mybatis:
  configuration:
    map-underscore-to-camel-case: true
